### ISSUE TITLE
Incompatible with Next JS SSR

### ISSUE THREAD

**Issue by wfortin** [seawind543/react-token-input#52]
Running `react-customize-token-input` in Next JS causes an error when server side rendering the component. I get `ReferenceError: self is not defined`. I have found similar libraries with the same issue. 

See https://stackoverflow.com/questions/64639839/typescript-webpack-library-generates-referenceerror-self-is-not-defined.

The solution is simple, I will suggest a PR for this.

Thank you.

**Comment by seawind543** [comment]
Hi @wfortin, 

Cool! Thank you for the issue report and provide a solution 👍
Let's fix it!
