### ISSUE TITLE
Need better documentation

### ISSUE THREAD

**Issue by iyinolu** [seawind543/react-token-input#68]
I'm currently trying to customize the token component. I have the props that allows for that on `TokenInput` component, but there is insufficient information on how to handle the data passed to `customizeTokenComponent` props on `TokenInput` component. For example how will the onDelete feature be inplemented on a customized container.

**Comment by seawind543** [comment]
Hi @iyinolu,

Version 2.0.0 had been officially released. You are welcome to make a trial, and any questions & feature requests are welcome.

Again, thanks for raising the issue to help TokenInput enhance 👍
